name: Deploy to Kind

on:
  push:
    branches:
      - main

jobs:
  kind:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Remove Conflicting Packages
      run: |
        sudo apt-get remove -y containerd containerd.io
        sudo apt-get autoremove -y

    - name: Install Docker Using Official Script
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh

    - name: Install Kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Create Kind Cluster
      run: kind create cluster

    - name: Pull Docker Image
      run: docker pull nikita1996rao/proloaf8:latest

    - name: Load Docker Image into Kind
      run: kind load docker-image nikita1996rao/proloaf8:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get services
