name: Deploy to Kind

on:
  push:
    branches:
      - main

jobs:
  kind:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Remove the Install Kind step if you're running this on a self-hosted runner where Kind is pre-installed

    - name: Create Kind Cluster
      run: kind create cluster

    - name: Check Disk Space Before Loading Image
      run: df -h

    - name: Clean Up Docker Environment
      run: |
        docker system prune -f

    - name: Pull Docker Image
      run: docker pull nikita1996rao/proloaf8:latest

    - name: Load Docker Image into Kind
      run: kind load docker-image nikita1996rao/proloaf8:latest

    - name: Check Disk Space After Loading Image
      run: df -h

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get services

    - name: Delete Kind Cluster
      if: always() # Ensure this step runs even if previous steps fail
      run: kind delete cluster
