name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create Kind cluster
        run: |
          kind create cluster --config kind-config.yaml
          kind get kubeconfig --internal > kind-kubeconfig.yaml

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ github.workspace }}/kind-kubeconfig.yaml
        run: |
          kubectl --kubeconfig=$KUBECONFIG apply -f deployment.yaml
