name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Kind cluster
        run: |
          kind create cluster --config kind-config.yaml

      - name: Deploy to Kubernetes
        run: |
          kind get kubeconfig --internal | kubectl --kubeconfig=- apply -f deployment.yaml

      - name: Verify deployment
        run: |
          kind get kubeconfig --internal | kubectl --kubeconfig=- get deployments
