name: Load Docker Image into Kind

on:
  push:
    branches:
      - main

jobs:
  load-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Create Kind Cluster
      run: kind create cluster --name my-cluster

    - name: Pull Docker Image
      run: docker pull nikita1996rao/proloaf8:latest

    - name: Load Docker Image into Kind
      run: kind load docker-image nikita1996rao/proloaf8:latest --name my-cluster
